### ISSUE TITLE
bt_vorgang partly returns empty / meaningless list columns

### ISSUE THREAD

**Issue by jkchl** [benjaminguinaudeau/tidybundestag#1]
Hello,

First of all, thanks a lot for making the parliamentary documentation of the Bundestag much more accessible!

I played around with all the different functions of your package and might have discovered an issue... when retrieving Vorgänge via bt_vorgang, some list columns appear to be empty or meaningless. For instance, when calling [Vorgang "78342"](https://dip.bundestag.de/vorgang/gesetz-zur-neuordnung-der-verantwortung-in-der-kerntechnischen-entsorgung/78342) via _bt_vorgang(id = "78342")_, the columns "sachgebiet", "zustimmungsbeduerftigkeit", and "initiative" only consist of _"list(`.y != .x` = c(TRUE, TRUE, TRUE))"_, _"list(`.y != .x` = c(TRUE, TRUE))"_, and _"list(`.y != .x` = c(TRUE, TRUE, TRUE))"_. 
However, when I retrieve the same Vorgang via _GET(url = "https://search.dip.bundestag.de/api/v1/vorgang/78342?apikey=N64VhW8.yChkBUIJeosGojQ7CSR2xwLf3Qy7Apw464")_, that information isn't missing. 
I observed this issue with other Vorgänge, as well. 

So, I am wondering if this an issue of one of the package's functions or if it's only an issue I have. 

Thanks a lot!

**Comment by benjaminguinaudeau** [comment]
Hi Jkchl, 

Thanks for pointing this out. I remember having the same issue in the past, but this was fixed with a later commit. 

I was not able to reproduce the error. Can you try to reinstall the package and see if the problem persists? 

```
devtools::install_github("benjaminguinaudeau/tidybundestag")
# Restart R to have a clean session
```

```
library(tidybundestag)
a <- bt_vorgang(id = "78342")

a$sachgebiet %>% dplyr::glimpse()
```

<img width="410" alt="Screenshot 2021-08-30 at 16 33 51" src="https://user-images.githubusercontent.com/29734292/131356056-61539172-c9b6-41fc-82b7-489059d9ce98.png">

**Comment by jkchl** [comment]
Thanks for your swift reply! As you suggested, I reinstalled the package several times now - in vain. It's still showing:

```
> a$sachgebiet %>% dplyr::glimpse()
List of 1
 $ : tibble [3 x 1] (S3: tbl_df/tbl/data.frame)
  ..$ .y != .x: logi [1:3] TRUE TRUE TRUE
```

I also reinstalled purrr and tibble as they seem to do most of the parsing work in your code, but that didn't help either. My R also seems to be up-to-date. I tried it on a different machine, as well - no success, unfortunately. 

If you are certain, that the problem doesn't stem from your code on github, do you have a suggestion what else I could try? 

___
Here's the complete code I ran, maybe it helps...

```
Restarting R session...

> devtools::install_github("benjaminguinaudeau/tidybundestag")
Downloading GitHub repo benjaminguinaudeau/tidybundestag@HEAD
√  checking for file 'C:\xxx\Temp\RtmpGCYJ8v\remotes32b846c125c4\benjaminguinaudeau-tidybundestag-877afc7/DESCRIPTION' (357ms)
-  preparing 'tidybundestag':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
   Omitted 'LazyData' from DESCRIPTION
-  building 'tidybundestag_0.0.0.9000.tar.gz'
   
Installiere Paket nach ‘C:/xxx/Documents/R/win-library/4.1’
(da ‘lib’ nicht spezifiziert)
* installing *source* package 'tidybundestag' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'tidybundestag'
    finding HTML links ... done
    bt_aktivitaet                           html  
    bt_drucksache                           html  
    bt_drucksache_text                      html  
    bt_person                               html  
    bt_plenarprotokoll                      html  
    bt_plenarprotokoll_text                 html  
    bt_vorgang                              html  
    bt_vorgangsposition                     html  
    pipe                                    html  
REDIRECT:topic	 %>% -> pipe.html [ FAIL ]
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
** testing if installed package can be loaded from final location
*** arch - i386
*** arch - x64
** testing if installed package keeps a record of temporary installation path
* DONE (tidybundestag)

Restarting R session...

> library(tidybundestag)
> a <- bt_vorgang(id = "78342", api_token = "N64VhW8.yChkBUIJeosGojQ7CSR2xwLf3Qy7Apw464")
√ Total number of retrievable units: 1 (Maximum set to 100)
√ Successfully retrieved 1 documents
    
> a$sachgebiet %>% dplyr::glimpse()
List of 1
 $ : tibble [3 x 1] (S3: tbl_df/tbl/data.frame)
  ..$ .y != .x: logi [1:3] TRUE TRUE TRUE
```

**Comment by benjaminguinaudeau** [comment]
Thanks for trying all this. I can replicate the error on my laptop. I'll investigate it and let you know when I find the error. 

Again, sorry for the inconvenience and thank you for helping me solve those issues!

**Comment by benjaminguinaudeau** [comment]
Alright, the culprit was a small rlang issue. 
I just committed a fix, can you please try reinstalling and let me know if this fixed the issue?

**Comment by jkchl** [comment]
It fixed the issue, thank you very much!
