### ISSUE TITLE
New URL For PDF

### ISSUE THREAD

**Issue by hejjoe** [benjaminguinaudeau/tidybundestag#2]
Sadly the Bundestag decided to change the URL of the documentation without using a URL redirection (e.g. with http status 301), so please update the URL manually in README.md. 

old: https://dip.bundestag.de/documents/informationsblatt_zur_dip_api_v01.pdf
new: https://dip.bundestag.de/documents/informationsblatt_zur_dip_api.pdf

Fun fact: The old version is still availabe here: https://web.archive.org/web/2021*/https://dip.bundestag.de/documents/informationsblatt_zur_dip_api_v01.pdf

**Comment by benjaminguinaudeau** [comment]
Thank you for pointing that out. 

I've just updated the Readme.
